version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend_container

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: backend_container
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
